#!/bin/sh

#You can change these two to match your directory structure.
new_dir=new_modules
old_dir=modules

#-------------------------------------------------------------------------
#
#  >>> Update module file
#
# This script is used to update a module file $1 in the modules directory
# only if it is different from the module file $1 in the new_modules
# directory. In this way, object files which depend on $1 need not
# be recompiled needlessly!
#
# (c) dylan jayatilaka, university of western australia, 1999-2001
# (c) daniel grimwood, university of western australia, 2000-2001
#
# $Id$
#
#-------------------------------------------------------------------------

name=$1
new_mod=new_modules/$name
old_mod=modules/$name

if [ -z $name ]; then
echo "Need the module file name as an argument to this script"
exit 1
fi
if [ ! -d $new_dir ]; then
 echo "Error: directory $new_dir does not exist!"
 exit 1
fi
if [ ! -d $old_dir ]; then
 echo "Error: directory $old_dir does not exist!"
 exit 1
fi

if [ ! -f $new_mod ]; then
   if [ -f $name ]; then
     /bin/mv $name $new_mod
   else 
      set name = `echo $name:r | tr a-z A-Z`.mod
      if [ -f $name ]; then
         /bin/mv $name $new_mod
      fi
   fi
fi

if [ -f $new_mod ]; then
 if [ -f $old_mod ]; then
  # for nice compilers
  echo $new_mod
  echo $old_mod
  if [ `cmp $new_mod $old_mod | wc -l` -eq 0 ]; then
   /bin/rm -f $new_mod
   echo "Keeping the old $name file"
  # for compaq compiler / tru64
  elif [ `cmp -l $new_mod $old_mod | perl -ne 'next if /^    2[567]/; print' | wc -l` -eq 0 ]; then
   /bin/rm -f $new_mod
   echo "Keeping the old $name file"
## this one untested!
#  # for compaq compiler / linux
#  elif [ `cmp -l $new_mod $old_mod | perl -ne 'next if /^    (4[89])|(5[01])/; print' | wc -l` -eq 0 ]; then
#   /bin/rm -f $new_mod
#   echo "Keeping the old $name file"
  else
   /bin/mv -f $new_mod $old_mod
   echo "Updating the old $name file"
  fi
 else
  /bin/mv -f $new_mod $old_mod
  echo "Creating a new $name file"
 fi
else
 echo "Error: module file $new_mod does not exist!"
 exit 1
fi
