#!/bin/csh -f
## make_navbar
## ! $Id$

echo '<HTML>'
echo '<HEAD>'
echo '  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">'
echo '  <META name="robots" content="noindex, nofollow">'
echo '  <TITLE>Tonto Navigation</TITLE>'
echo '<BASE TARGET="main">'
echo '</HEAD>'
echo '<body BGCOLOR="#FFFBF0">'
echo '<BR>'
echo '<DIV ALIGN=CENTER>'
echo '</A><IMG SRC="WWW/tonto_nav.gif" HEIGHT=61 WIDTH=113 BORDER="1"></A>'
echo '<DL COMPACT>'

echo '<BR>'
echo '<HR NOSHADE WIDTH=80%>'
echo '      <DT><A HREF="WWW/index.html">What is TONTO?</A>'
echo '      <DT><A HREF="foofiles">.foo source files</A>'
echo '      <DT><A HREF="f90files">.f90 source files</A>'

echo '<BR>'
echo '<HR NOSHADE WIDTH=80%>'
echo '<BR>SCRIPTS AND UTILITIES<BR><BR>'
echo '      <DT><A HREF="scripts/macros">macros</A>'
echo '      <DT><A HREF="scripts/Makefile">Makefile</A>'
echo '      <DT><A HREF="scripts/make_dependfile">make_dependfile</A>'
echo '      <DT><A HREF="scripts/make_dependfile.script">make_dependfile.script</A>'
echo '      <DT><A HREF="scripts/update_module_file">update_module_file</A>'
echo '      <DT><A HREF="scripts/foo.perl">foo.perl</A>'
echo '      <DT><A HREF="scripts/foo2html">foo2html</A>'
echo '      <DT><A HREF="scripts/foo2html.script">foo2html.script</A>'
echo '<BR>'
echo '<HR NOSHADE WIDTH=80%>'
echo '<BR>MODULES<BR><BR>'

foreach i ($argv) 
   echo '<DT><A HREF="htmlfiles/'$i'_short.html">'$i'</A> <A HREF="foofiles/'$i'.foo">.foo</A>'
end

echo '</DL>'
echo '</DIV>'
echo '</BODY>'
echo '</HTML>'
